deployments:
    environmentMapping:
      development:
        - "dev*"
      testing:
        - "test"
      staging:
        - "Pre-Prod"
        - "staging"
      production:
        - "Production"
        - "PROD"