# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    needs: build
    runs-on: windows-latest
    environment: PROD
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.GITTOKEN }}    
    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: '5.x'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Replace values in JSON file
      uses: tnikFi/json-file-transform@v1
      with:
       files: '**/appsettings.json'
       key-value-pairs: |
        ConnectionStrings.Default=${{ secrets.DB_CONNECTION_STRING }}
        Smtp.Host=${{ secrets.EMAIL_HOST }}
        Smtp.Port=${{ secrets.EMAIL_PORT }}
        Smtp.Ssl=${{ secrets.EMAIL_SSL }}
        Smtp.User=${{ secrets.EMAIL_USER }}
        Smtp.Password=${{ secrets.EMAIL_PASSWORD }}
    - name: Publish & Deploy
      run: dotnet publish Server/MyVideoResume.Server.csproj /p:PublishProfile=webdeploy.pubxml /p:Password=${{secrets.DEPLOYPASSWORD}}